//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciIsleri.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OIDbEntities : DbContext
    {
        public OIDbEntities()
            : base("name=OIDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolumler> Bolumlers { get; set; }
        public virtual DbSet<Cinsiyetler> Cinsiyetlers { get; set; }
        public virtual DbSet<Dersler> Derslers { get; set; }
        public virtual DbSet<Notlar> Notlars { get; set; }
        public virtual DbSet<Ogrenciler> Ogrencilers { get; set; }
        public virtual DbSet<Ogretmenler> Ogretmenlers { get; set; }
        public virtual DbSet<Sehirler> Sehirlers { get; set; }
        public virtual DbSet<Sınıflar> Sınıflar { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Uyruklar> Uyruklars { get; set; }
        public virtual DbSet<Kullanıcılar> Kullanıcılar { get; set; }
    }
}
