//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciIsleri.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanıcılar
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Kullanıcı Adı boş geçilemez.")]
        public string KullanıcıAdi { get; set; }
        [Required(ErrorMessage ="Şifre boş geçilemez.")]
        public string Sifre { get; set; }
        public Nullable<int> OgretmenID { get; set; }
    
        public virtual Ogretmenler Ogretmenler { get; set; }
    }
}
