//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciIsleri.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ogretmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogretmenler()
        {
            this.Derslers = new HashSet<Dersler>();
            this.Notlars = new HashSet<Notlar>();
            this.Kullanıcılar = new HashSet<Kullanıcılar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BolumID { get; set; }
        [Required(ErrorMessage ="Ad Soyad boş geçilemez.")]
        public string Adsoyad { get; set; }
        public string Fotograf { get; set; }
        [Required(ErrorMessage ="Doğum tarihi boş geçilemez.")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> DogumYeri { get; set; }
        public Nullable<int> CinsiyetID { get; set; }
        [Required(ErrorMessage = "Adres boş geçilemez.")]
        public string Adres { get; set; }
        [Required(ErrorMessage ="Telefon numarası boş geçilemez.")]
        public string Tel { get; set; }
        [Required(ErrorMessage ="Mail adresi boş geçilemez.")]
        public string Mail { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Cinsiyetler Cinsiyetler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dersler> Derslers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notlar> Notlars { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanıcılar> Kullanıcılar { get; set; }
    }
}
