//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciIsleri.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.Notlars = new HashSet<Notlar>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="Ad ve Soyad boş geçilemez.")]
        public string Adsoyad { get; set; }
        [Required(ErrorMessage ="TC Kimlik NO boş geçilemez")]
        public string TCNo { get; set; }
        public string Fotograf { get; set; }
        public Nullable<int> CinsiyetID { get; set; }
        [Required(ErrorMessage ="Adres boş geçilemez.")]
        public string Adres { get; set; }
        [Required(ErrorMessage ="Telefon numarası boş geçilemez.")]
        public string TelNo { get; set; }
        [Required(ErrorMessage ="Mail adresi boş geçilemez.")]
        public string Mail { get; set; }
        [Required(ErrorMessage ="Doğum tarihi boş geçilemez.")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<int> BolumID { get; set; }
        public Nullable<int> DogumYeri { get; set; }
        public Nullable<int> Sınıf { get; set; }
        public Nullable<int> UyrukID { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Cinsiyetler Cinsiyetler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notlar> Notlars { get; set; }
        public virtual Sehirler Sehirler { get; set; }
        public virtual Sınıflar Sınıflar { get; set; }
        public virtual Uyruklar Uyruklar { get; set; }
    }
}
